### ISSUE TITLE
low frame rate when recording two velodynes at the same time

### ISSUE THREAD

**Issue by JereKnuutinen** [ros-drivers/velodyne#559]
I have two veloduynes and I have used them two years with out any problems. Lately I changed to ros2 jazzy (ubuntu 24.04, cyclone _dds) and for some reason my velodynes are not anymore producing data (velodyne_poinst) at 10 Hz when recording BOTH topics to bag file. If I only record one velodyne_topic to bag file then it gives 10 Hz. Same also happens if I try to ros2 topic hz both topics at the same time. 

Here is my launch file
```
import os
import yaml

import ament_index_python.packages
import launch
import launch_ros.actions


def generate_launch_description():
    driver_share_dir = ament_index_python.packages.get_package_share_directory('velodyne_driver')
    driver_params_file = os.path.join(driver_share_dir, 'config', 'VLP16-velodyne_driver_node-params_multi.yaml')
    velodyne_driver_node_left = launch_ros.actions.Node(package='velodyne_driver',
                                                   executable='velodyne_driver_node',
                                                   namespace='lidar_left',
                                                   output='both',
                                                   parameters=[driver_params_file])

    velodyne_driver_node_right = launch_ros.actions.Node(package='velodyne_driver',
                                                   executable='velodyne_driver_node',
                                                   namespace='lidar_right',
                                                   output='both',
                                                   parameters=[driver_params_file])


    convert_share_dir = ament_index_python.packages.get_package_share_directory('velodyne_pointcloud')
    convert_params_file = os.path.join(convert_share_dir, 'config', 'VLP16-velodyne_transform_node-params.yaml')
    
    with open(convert_params_file, 'r') as f:
        convert_params = yaml.safe_load(f)['velodyne_transform_node']['ros__parameters']
    convert_params['calibration'] = os.path.join(convert_share_dir, 'params', 'VLP16db.yaml')
    velodyne_convert_node_left = launch_ros.actions.Node(package='velodyne_pointcloud',
                                                    executable='velodyne_transform_node',
                                                    namespace='lidar_left',
                                                    output='both',
                                                    parameters=[convert_params])

    velodyne_convert_node_right = launch_ros.actions.Node(package='velodyne_pointcloud',
                                                    executable='velodyne_transform_node',
                                                    namespace='lidar_right',
                                                    output='both',
                                                    parameters=[convert_params])

    laserscan_share_dir = ament_index_python.packages.get_package_share_directory('velodyne_laserscan')
    laserscan_params_file = os.path.join(laserscan_share_dir, 'config', 'default-velodyne_laserscan_node-params.yaml')
    
    velodyne_laserscan_node_left = launch_ros.actions.Node(package='velodyne_laserscan',
                                                      executable='velodyne_laserscan_node',
                                                      namespace='lidar_left',
                                                      output='both',
                                                      parameters=[laserscan_params_file])

    velodyne_laserscan_node_right = launch_ros.actions.Node(package='velodyne_laserscan',
                                                      executable='velodyne_laserscan_node',
                                                      namespace='lidar_right',
                                                      output='both',
                                                      parameters=[laserscan_params_file])


    return launch.LaunchDescription([velodyne_driver_node_left,
                                     velodyne_driver_node_right,
                                     velodyne_convert_node_left,
                                     velodyne_convert_node_right,
                                     velodyne_laserscan_node_left,
                                     velodyne_laserscan_node_right

                                    #  launch.actions.RegisterEventHandler(
                                    #      event_handler=launch.event_handlers.OnProcessExit(
                                    #          target_action=velodyne_driver_node,
                                    #          on_exit=[launch.actions.EmitEvent(
                                    #              event=launch.events.Shutdown())],
                                    #      )),
                                     ])
```

and config', 'VLP16-velodyne_driver_node-params_multi.yaml

```
lidar_left/velodyne_driver_node:
    ros__parameters:
        device_ip: 192.168.1.201
        gps_time: false
        time_offset: 0.0
        enabled: true
        read_once: false
        read_fast: false
        repeat_delay: 0.0
        frame_id: velodyne1
        model: VLP16
        rpm: 600.0
        port: 2368
        timestamp_first_packet: false
        
lidar_right/velodyne_driver_node:
    ros__parameters:
        device_ip: 192.168.1.202
        gps_time: false
        time_offset: 0.0
        enabled: true
        read_once: false
        read_fast: false
        repeat_delay: 0.0
        frame_id: velodyne2
        model: VLP16
        rpm: 600.0
        port: 2369
        timestamp_first_packet: false
```

Can somebody help me understand why is this happening.
